export const Fonts = {
  default: "Montserrat-Regular",
  medium: "Montserrat-Medium",
  bold: "Montserrat-Bold",
  semiBold: "Montserrat-SemiBold",
  thin: "Montserrat-Thin",
};
export const Colors = {
  cancelTxtColor: "#D7D7D7",
  cancelBackground: "#FFD1D1",
  starBackground: "#F5F5F5",
  primaryOne: "#0F73EE",
  primaryTwo: "#005496",
  primaryThree: "#0074B2",
  primaryFour: "#38C6F4",
  primaryFive: "#E5F9FF",
  primarySix: "#F7F9FF",
  primarySeven: "#D9E7FD",
  primaryEight: "#D3AF37",
  secondaryOne: "#C644FC",
  secondaryTwo: "#FCE697",
  secondaryThree: "#FCF7E3",
  secondaryFour: "#FF0000",
  neutralLightOne: "#F7F9FF",
  neutralLightTwo: "#EDF1F2",
  neutralLightThree: "#F0F0F0",
  neutralLightFour: "#DADADA",
  neutralLightFive: "#ffffff",
  neutralDarkOne: "#000000",
  neutralDarkTwo: "#020433",
  neutralDarkThree: "#404B69",
  neutralDarkFour: "rgba(63, 71, 82, 0.5)",
  neutralDarkFive: "#95A0B6",
  neutralDarkSix: "#979797",
  success: "#08C299",
  timerTextC1: "#404040",
  calenderioBack: "#F3D9FE",
};
